[tool.poetry]
name = "p-timeit"
version = "0.1.0"
description = "A prettier timeit."
authors = ["Abhinav Omprakash"]
license="BSD-3-Clause"
readme="README.md"
homepage="https://github.com/AbhinavOmprakash/py-htminify"
repository="https://github.com/AbhinavOmprakash/py-htminify"
keywords=["Timer", "timeit"]
include=[
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
